CREATE TABLE Memo (
	seq INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	WDATE DATE NOT NULL,
	CONTENT TEXT NOT NULL,
	WRITER_ID VARCHAR(255) NOT NULL,
	USER_ID VARCHAR(255) NOT NULL,
	ISREAD tinyint(1) NOT NULL,
	RECEIVE_DEL tinyint(1) NOT NULL,
	SEND_DEL tinyint(1) NOT NULL,
	PRIMARY KEY(seq),
	FOREIGN KEY(WRITER_ID) REFERENCES member(id) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(USER_ID) REFERENCES member(id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;